package com.example.distancetracker.util

object Constants {
    const val PERMISSION_LOCATION_REQUEST_CODE=1
    const val BACKGROUND_PERMISSION_LOCATION_REQUEST_CODE=2

    const val NOTIFICATION_CHANNEL_ID="NOTIFICATION_CHANNEL_ID"
    const val NOTIFICATION_CHANNEL_NAME="NOTIFICATION_CHANNEL_NAME"
    const val NOTIFICATION_ID=3

    const val ACTION_START_FOREGROUND_SERVICE="ACTION_START_FOREGROUND_SERVICE"
    const val ACTION_STOP_FOREGROUND_SERVICE="ACTION_STOP_FOREGROUND_SERVICE"

    const val LOCATION_UPDATE_INTERVAL=4000L
    const val LOCATION_FASTEST_UPDATE_INTERVAL=2000L

}